services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'nodejs-example-api'
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql
    container_name: 'nodejs-example-mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
